version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - maria_db
    links:
      - maria_db:app_db
  maria_db:
    image: "mariadb:10.5.9"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: employee
      MYSQL_USER: employeemanager
      MYSQL_PASSWORD: employee-test
      MYSQL_ROOT_PASSWORD: YHM4K82U4Gd49H
